[platformio]
default_envs = gateway

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
monitor_speed = 115200
upload_protocol = picotool

lib_deps =
    jgromes/RadioLib

[env:nodo1]
build_flags =
    -D DEVICE_MODE_TX
    -D NODE_ID=1
    -D DEVICE_NAME=\"NODO_1\"

[env:nodo2]
build_flags =
    -D DEVICE_MODE_TX
    -D NODE_ID=2
    -D DEVICE_NAME=\"NODO_2\"

[env:gateway]
build_flags =
    -D DEVICE_MODE_GATEWAY
    -D NODE_ID=0
    -D DEVICE_NAME=\"GATEWAY\"